name: docker-workflow

on:
  workflow_call:
    inputs:
      docker_repository:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKER_REGISTRY:
        required: true

jobs:
  build:
    name: docker_build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      id: build-image
      env:
        DOCKER_REPOSITORY: ${{ inputs.docker_repository }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        echo "Building docker image $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
        docker build --build-arg SERVICE_NAME=$DOCKER_REPOSITORY -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
        echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"

    - name: Push the image to Docker Hub
      id: push-image
      env:
        IMAGE: ${{ steps.build-image.outputs.image }}
      run: |
        echo "Pushing image $IMAGE to Docker Hub..."
        docker push $IMAGE
        echo "Done"
        echo "::set-output name=image::$IMAGE"
